#!/bin/bash

source ~/dxnn_sdk/dxnn_sdk_env.sh

pushd ${DXNN_HOST_DRIVER_DIR}/modules

sudo ./module_insert.sh

sleep 1
#sudo ../utils/script/pcie_rescan.sh

${DXNN_RUNTIME_DIR}/bin/dxrt-cli -s

popd
