#!/bin/bash

DEFAULT_MODEL=2663
pushd ${DXNN_RUNTIME_DIR}


default_repeat=1

repeat=${1:-$default_repeat}

echo "::: Stress Run Test :::"


if [ $? -ne 0 ]; then
    echo "fail - pcie"
    exit 1
fi


for ((i=1; i<=repeat; i++))
do
    echo "Repeats: $i / $repeat"
    date +"%m/%d/%Y %I:%M:%S %p"

    run_model -m /models/m1a/${DEFAULT_MODEL}/YoloV7/YoloV7.dxnn -l 1000 -b | strings | grep FPS

    if [ $? -ne 0 ]; then
        echo "fail - model"
        exit 1
    fi

    #temperature=$(dxrt-cli -s | grep -oP 'temperature \K[0-9]+' | sed -n '1p')
    #echo $temperature

done

popd
