SRC_DIR := dkms/source/dx-module-b/dx-module-b-1.0

all:
	$(MAKE) -C $(SRC_DIR) all

install:
	$(MAKE) -C $(SRC_DIR) install

uninstall:
	$(MAKE) -C $(SRC_DIR) uninstall

clean:
	$(MAKE) -C $(SRC_DIR) clean
