SRC_DIR := dkms/source/dx-module-a/dx-module-a-1.0

all:
	$(MAKE) -C $(SRC_DIR) all

install:
	$(MAKE) -C $(SRC_DIR) install

uninstall:
	$(MAKE) -C $(SRC_DIR) uninstall

clean:
	$(MAKE) -C $(SRC_DIR) clean
